// react-package/src/extensions/copy-button/index.ts
import { useEffect } from "react"
import { PrismEditor } from "../../types"
import { createTemplate } from "../../utils/local"
import { addOverlay, setSelection } from "../../utils"
import { addListener, doc } from "../../core"

/**
 * Creates a static copy button that can be added to the overlays of an editor or code
 * block. The `firstChild` of the element returned is the button itself.
 */
const createCopyButton = /* @__PURE__ */ createTemplate(
	'<div style=display:flex;align-items:flex-start;justify-content:flex-end><button type=button dir=ltr style=display:none class=pce-copy><svg width=1.2em aria-hidden=true viewBox="0 0 16 16" overflow=visible stroke-linecap=round fill=none stroke=currentColor><rect x=4 y=4 width=11 height=11 rx=1 /><path d="m12 2a1 1 0 00-1-1H2A1 1 0 001 2v9a1 1 0 001 1">',
)

/**
 * Hook that adds a copy button to the editor. Probably best used with a read-only editor.
 * Requires styles from `prism-react-editor/copy-button.css` to work.
 *
 * By default, the copy button is only shown when the editor is hovered. To always show
 * it, change the default opacity with the following CSS:
 *
 * ```less
 * button.pce-copy {
 *   opacity: 1; // or a lower value for a semi-transparent button
 * }
 * ```
 *
 * @param editor Editor to add the copy button to.
 * @param label `aria-label` for the button. Defaults to `"Copy"`.
 * @param copiedLabel Temporary `aria-label` for the button after it has been clicked.
 * Defaults to `"Copied!"`.
 */
const useCopyButton = (editor: PrismEditor, label = "Copy", copiedLabel = "Copied!") => {
	useEffect(() => {
		const container = createCopyButton()
		const btn = container.firstChild as HTMLButtonElement
		const setLabel = (label: string) => btn.setAttribute("aria-label", label)

		addListener(btn, "click", () => {
			setLabel(copiedLabel)
			if (!navigator.clipboard?.writeText(editor.extensions.folding?.fullCode ?? editor.value)) {
				editor.textarea!.select()
				doc!.execCommand("copy")
				setSelection(editor, 0)
			}
		})

		addListener(btn, "pointerenter", () => setLabel(label))

		setLabel(label)

		addOverlay(editor, container)
		return () => container.remove()
	}, [label, copiedLabel])
}

export { useCopyButton, createCopyButton }

// solid-package/src/extensions/copy-button/index.ts
import { template } from "solid-js/web"
import { Extension } from "../../types"
import { doc } from "../../core"
import { setSelection } from "../../utils"

/**
 * Creates a static copy button that can be added to the overlays of an editor or code
 * block. The `firstChild` of the element returned is the button itself.
 */
const createCopyButton = /* @__PURE__ */ template(
	'<div style=display:flex;align-items:flex-start;justify-content:flex-end><button type=button dir=ltr style=display:none class=pce-copy><svg width=1.2em aria-hidden=true viewBox="0 0 16 16" overflow=visible stroke-linecap=round fill=none stroke=currentColor><rect x=4 y=4 width=11 height=11 rx=1 /><path d="m12 2a1 1 0 00-1-1H2A1 1 0 001 2v9a1 1 0 001 1">',
)

/**
 * Extension that adds a copy button to the editor. Probably best used with a read-only
 * editor. Requires styles from `solid-prism-editor/copy-button.css` to work.
 *
 * By default, the copy button is only shown when the editor is hovered. To always show
 * it, change the default opacity with the following CSS:
 *
 * ```less
 * button.pce-copy {
 *   opacity: 1; // or a lower value for a semi-transparent button
 * }
 * ```
 *
 * @param label `aria-label` for the button. Defaults to `"Copy"`.
 * @param copiedLabel Temporary `aria-label` for the button after it has been clicked.
 * Defaults to `"Copied!"`.
 */
const copyButton = (label = "Copy", copiedLabel = "Copied!"): Extension => {
	return editor => {
		const container = createCopyButton()
		const btn = container.firstChild as HTMLButtonElement
		const setLabel = (label: string) => btn.setAttribute("aria-label", label)

		btn.addEventListener("click", () => {
			setLabel(copiedLabel)
			if (!navigator.clipboard?.writeText(editor.extensions.folding?.fullCode ?? editor.value)) {
				editor.textarea.select()
				doc!.execCommand("copy")
				setSelection(editor, 0)
			}
		})

		btn.addEventListener("pointerenter", () => setLabel(label))

		setLabel(label)

		return container
	}
}

export { createCopyButton, copyButton }
